name: Rust Documentation CI

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build documentation
      run: cargo doc --no-deps --all-features

    - name: Publish to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages
        folder: target/doc 
        token: ${{ secrets.GH_TOKEN }}  
