name: Rust CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          rustup toolchain install stable
          rustup default stable
          cargo test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Release
        run: |
          rustup toolchain install stable
          rustup default stable
          cargo build --release
        # Artifact path: target/release

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Documentation
        run: |
          rustup toolchain install stable
          rustup default stable
          cargo doc
        # Artifact path: target/doc

  publish:
    runs-on: ubuntu-latest
    needs: [build, rustdoc]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Public Directory
        run: mkdir public

      - name: List
        run: ls -l

      - name: Copy Documentation
        run: mv target/doc public/doc

      - name: Copy Binary
        run: mv target/release/* public/
        # Assuming the binary file has a predictable name

      - name: Archive Public Directory
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

